### ISSUE TITLE
Focusing the window opens URL links

### ISSUE THREAD

**Issue by stewartlord** [elementary/terminal#104]
Terminal recognizes URLs and turns them into clickable links. Add a setting to disable this feature. I often click on a terminal window to give it focus and inadvertently open a link.

**Comment by danrabbit** [comment]
Sounds like what we want isn't to add a setting, but to fix it so that giving the window focus doesn't also trigger links

**Comment by Philip-Scott** [comment]
this is actually "normal" behavior across all apps though. (Gtk and non Gtk) Clicking on something even if it's unfocused both focuses the window and executes the action

**Comment by danrabbit** [comment]
Hm I guess you're right there

**Comment by jeremypw** [comment]
It may be worth considering whether there are any "dangerous" or expensive operations that should not occur on focus-in, but most operations should be undoable anyway.

**Comment by mgraff** [comment]
I think it should be safer to use a modifier (e.g. CTRL + click) to open a link.
For example, I often open links whereas I just want to select the URL to copy/paste it.

**Comment by jeremypw** [comment]
I tend to agree. At least an active link should be coloured distinctively or permanently underlined rather than just appearing underlined when hovered.  This would help avoid inadvertent clicking.

**Comment by reece146** [comment]
This does not seem to have been resolved/closed.

Having URLs in a terminal window that are "live" is potentially dangerous depending on what is being displayed in the window. 

CTRL-Click seems to be a good work around - other OS do it this way.

If there are concerns with changing the existing, default behaviour I'd be content with something "experimental" hidden in gsettings as long as it was there to modify. Unfortunately, at this time my workaround for this issue is installing and using Tilix instead of Terminal (URLS are not live).
