### ISSUE TITLE
New Window on right click from Dock doesn't work

### ISSUE THREAD

**Issue by dkotrada** [elementary/terminal#111]
1. Make shure terminal icon is docked on Dock. 
2. Right click on terminal icon -> New Window

Expected: New terminal window opens.
Behavior: It opens a new tab in opened terminal window.

**Comment by oblakeerickson** [comment]
I'm on Loki 0.4.1 and I can't duplicate this. I already have some terminal windows open and when I right click and choose "New Window" a new window appears.

**Comment by jeremypw** [comment]
Further investigation showed that the current development version, this bug occurs if Terminal is initially opened by Files but not if it is initially opened from the dock.

**Comment by jeremypw** [comment]
May be related to recent RDNN changes.

**Comment by tvale** [comment]
This began happening to me on Elementary OS 5.1 after the update to Terminal 5.5.0.

## Describe the bug
Using the Terminal's "New Window" on the dock opens a new tab instead of a new window.

### To Reproduce
Steps to reproduce the behavior:
1. See screen recording.

### Expected behavior
A new Terminal window instead of a new tab.

### Screenshots or screen recordings
![](https://github.com/tvale/tvale.github.io/raw/master/dumpster/elementary-5.1_terminal-5.5.0_bug.gif)

## Platform Information
![](https://github.com/tvale/tvale.github.io/raw/master/dumpster/elementary-5.1_about.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by tvale** [comment]
Fixed today when I updated to Terminal 5.5.1.
