### ISSUE TITLE
Two tabs when open from terminal

### ISSUE THREAD

**Issue by Djaler** [elementary/terminal#245]
Steps to reproduce:
1) Clear all exists tabs in terminal and close it.
2) Go to Files and select Open In -> Terminal

Expected: Only one tab with shell in selected directory

Actual: Two tabs (first with shell in selected directory and second in previous)

**Comment by jlnr** [comment]
Maybe another side of the same issue? When I close my terminal window by closing all tabs, then restart the app, the new window restores my last tab, instead of giving me a "default tab" in the home folder. This is different from how it works in web browsers, where closing windows by closing all tabs will properly "forget" them.

**Comment by jlnr** [comment]
I can reproduce this. Generally I don't think it's bad that previous tabs are restored (and not lost) when opening Terminal from Files. See also #234

Another side of the same issue: When I close my terminal window by closing all tabs, then restart the app, the new window restores my last tab, instead of giving me a "default tab" in the home folder. This is different from how it works in web browsers, where closing windows by closing all tabs will properly "forget" them.

**Comment by jeremypw** [comment]
If #234 were merged, then it would also fix this issue.
