### ISSUE TITLE
What about a move tab shortcut?

### ISSUE THREAD

**Issue by Blast-City** [elementary/terminal#322]
Hi.  

Right know you can select a tab by pressing Ctrl+Shift+Left/Right.  

What if there was also a shortcut to move tabs?

Ctrl+Shift+Up/Down , Ctrl+Alt+Left/Right or Ctrl+Shift+Alt+Left/Right.

**Comment by Blast-City** [comment]
Thanks.

**Comment by jeremypw** [comment]
Needs UX team decision on what shortcut to use (and whether another shortcut is desirable).  Ideally other core apps using a notebook should implement the same shortcut.

**Comment by janxkoci** [comment]
Actually most apps I know (Files, Nautilus, Thunar, Sublime text, web browsers like Epiphany, Firefox, Chrome, all terminal emulators with tabs, like gnome terminal, tilix etc, the list goes on) use these shortcuts:

- **Ctrl+PgUp / Ctrl+PgDn** --> switch to previous / next tab
- **Ctrl+Shift+PgUp / Ctrl+Shift+PgDn** --> move current tab left / right

I like this, because I have PgUp & PgDn keys right above my arrow keys, so I can use right Ctrl to easily navigate tabs in _most_ apps with right hand, just moving quickly from a touchpad. The _only_ app I regularly use where this doesn't work is - guess what - the elementary Terminal :confused: (also Code, but I rarely use it for anything).
