### ISSUE TITLE
Dark style is low constrast

### ISSUE THREAD

**Issue by uncertainquark** [elementary/terminal#373]
The default color scheme for the terminal is low contrast. I'm not sure if it's the somewhat small font size or the dull background color, but some combo of factors is making things a bit more difficult to read in the terminal than other apps. It is most evident in sunlight.

Here I put elementary and gnome terminal apps side-by-side to make the difference in contrast clear. 

![Screenshot from 2019-05-14 19-32-38](https://user-images.githubusercontent.com/22585732/57704238-22e70380-767f-11e9-887b-f34bcf2f6044.png)

**Comment by cassidyjames** [comment]
I agree it's a bit low contrast (partially due to the transparency on top of a white background), and we should look at increasing it a bit. However, I also know the lower contrast look is at least a bit intentional as it can help reduce eye strain, and we ship a high contrast and light mode as well if that's preferred.

Regarding GNOME Terminal, it's slightly more contrasty but also has a lighter background. According to WCAG 2.0 guidelines, both are just AA compliant, and not AAA compliant.

## GNOME Terminal

![image](https://user-images.githubusercontent.com/611168/57719252-8ef44800-763c-11e9-9719-8096d8aa4a77.png)

## elementary Terminal

(over a white background)

![image](https://user-images.githubusercontent.com/611168/57719408-ec889480-763c-11e9-928a-b94203244486.png)
