### ISSUE TITLE
Can only open one terminal window with super+t shortcut

### ISSUE THREAD

**Issue by GammaGames** [elementary/terminal#463]
After the latest releases pressing the `Super`+`T` shortcut correctly opens a new terminal with a single tab, but pressing the shortcut again does nothing. It does print a warning in `/var/log/syslog` though.

### To Reproduce
1. Use the terminal shortcut
2. Use the terminal shortcut again

### Expected behavior
A new tab (or window, if the user prefers that) should be opened.

### Logs
```
Jan 14 09:34:27 jl-eos gala.desktop[3491]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x580000a (sudo tail )
```

## Platform Information
![image](https://user-images.githubusercontent.com/7832163/72363296-d5111800-36b1-11ea-9102-a2e3b19c6e8f.png)

- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
This is because system-level shortcuts just execute the app without any flags (not an issue with Terminal) - equivalent to primary-clicking on the dock icon.  To work around this you need to create a custom shortcut using Switchboard/Keyboard/Shortcuts/Custom. The required command is `io.elementary.terminal -n`  Agree to reassign the Super+T shortcut or use another of your choice.

If you think all system-level application launching shortcuts should open a new window everytime you would have to file an issue against (presumably) the switchboard-plugin-keyboard.

**Comment by jeremypw** [comment]
I am going to close this as "Out of Scope" since changing this behaviour within Terminal would introduce inconsistency with other native apps.

**Comment by GammaGames** [comment]
Ah, I agree in that case. Though I do think the default system shortcut should be changed to open a new window/tab since that has always been the behavior. Thank you!

**Comment by jeremypw** [comment]
Looking at the code, it is the window manager (Gala) that actually launches apps in response to system-level shortcuts using the default desktop action for that app.  The switchboard plug just changes settings in `org.gnome.settings-daemon.media-keys.custom-keybbindings/...`.

**Comment by GammaGames** [comment]
Is there a setting to prefer new tabs, instead of new windows? `-n` only opens windows and I don't see any flag in the help that would open a new tab in an existing window

**Comment by jeremypw** [comment]
The default behaviour is to open a new tab if there is an existing window and you supply a path with `-w` flag.
