### ISSUE TITLE
Administrator Paste Dialog doesn't give focus to "Paste"

### ISSUE THREAD

**Issue by alex285** [elementary/terminal#466]
## Describe the bug
When we paste a "sudo" command, Terminal opens a dialog for confirmation; Using the keyboard we will most probably quickly press "Enter" to confirm the paste, but instead the focus goes to the checkbox, rather to "Paste Anyway" button

![elementary-bug](https://user-images.githubusercontent.com/11244308/72591260-6083e680-3908-11ea-9dce-41998a49bec9.png)

### To Reproduce
1. Type "sudo ls" and copy it
2. Paste it on a Terminal
3. Confirmation Dialog opens
4. Press Enter to confirm
5. You actually disable the checkbox

### Expected behavior
Enter should "Paste Anyway"

### Others
If we disable the confirmation (`unsafe-paste-alert`) from the checkbox, how we are supposed to enable it again? I mean outside using GSettings directly, dconf-editor etc..

**Comment by tintou** [comment]
The "Paste Anyway" is a destructive-action, the default button should be "Don't Paste" this dialog is here to be read not to be skipped over and over

**Comment by alex285** [comment]
@tintou I mostly see a "warning" when you paste with "sudo", which might be a good idea to have an additional step, because sometimes you can copy/paste quickly something, without even noticing it uses "sudo" 

Defaulting it to "Dont Paste" might be so annoying that someone will skip this dialog all together from the checkbox -that I assume you agree it shouldn't get focus anyway, correct?

**Comment by vikasnataraja** [comment]
I've noticed that the default elementary behavior is to err the side of NOT doing something. For example, if you get a dialog box with two options at the bottom - `Cancel` and `OK`, hitting Enter defaults to selecting `Cancel` instead of `OK`. Coming from Windows, this seems a bit unusual to me and it would be nice to have a system settings option that allows us to change dialog box popup selections to `OK` or similar options. But that would mean this issue belongs on the @[elementary/switchboard-plug-notifications](github.com/elementary/switchboard-plug-notifications) or some other repo.

**Comment by cassidyjames** [comment]
@alex285 
>If we disable the confirmation (unsafe-paste-alert) from the checkbox, how we are supposed to enable it again? I mean outside using GSettings directly, dconf-editor etc..

That's an entirely separate issue. Please open it as such.

@vikasnataraja a system-wide setting to change a fundamental part of the HIG doesn't really make sense. For non-destructive things, we do typically mark the affirmative action as the default. But for destructive things, we avoid having the destructive action selected by default

**Comment by vikasnataraja** [comment]
@cassidyjames  That makes sense, yes. I think in terms of security, I do like it the way it is but it might take some time to get used to if you are a new user.
