### ISSUE TITLE
Separate zoom level for different windows

### ISSUE THREAD

**Issue by alexeyten** [elementary/terminal#480]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
I have laptop and external monitor both have the same resolution but different screen size. When I open two terminal windows, one on laptop screen and another on external screen they have the same zoom level so either text on laptop is too tiny or text on monitor is too big.

I'd like to change zoom level on both windows independently.

**Comment by jeremypw** [comment]
This seems to be a reasonable use case but raises the question of how to save the state.  At the moment, only one state is restored - that of the last window that is closed (regardless of the order of opening).

**Comment by alexeyten** [comment]
I’m ok with wrong zoom on opening new window.
The problem is when I change zoom in one window it’s automatically synchronized in another window.

**Comment by jdz** [comment]
I tried ElementaryOS and this feature was basically a major turn-off for me.  Is there any written rationale of the current behaviour so I can understand the reasoning?

I personally find it odd to have a key binding to change the default font size.  Font setting in preferences, or maybe even system-wide font setting for monospace font.  But when I do want to change the font size in a terminal it's usually because the content does not fit in the current window and/or the lines wrap too much and hence the content becomes unreadable.  In this case I want to reduce the font size for the current terminal window only, and it makes no sense to change the text size in all other windows.

Might it be reasonable to have this behaviour as a (hidden) setting?

**Comment by jeremypw** [comment]
How should zoom levels apply to individual tabs?

**Comment by jdz** [comment]
> How should zoom levels apply to individual tabs?

Window size remains the same, text size in that one particular tab changes.  Text size in all other tabs stays the same.

The only terminal applications that do this one thing right is Terminal.app on macOS, and Konsole in KDE.  Not sure about iTerm.

**Comment by jeremypw** [comment]
This is fairly trivial to achieve (just remove one line of code) but that stops the current zoom value being saved in the settings.  It should be possible to save/restore zoom settings per tab as well though.  Another question then arises - what should the app menu popover show?  At present there is a single zoom control but if each tab has its own zoom value presumably a zoom control per tab would be required??

**Comment by jeremypw** [comment]
Or better it shows the zoom value of the active tab. Maybe with a checkbox "Apply to all tabs"

**Comment by jdz** [comment]
My reasoning is that the zoom level set using keyboard shortcuts is ephemeral.  If the user wants to change the default zoom level (font size), they should be able to do it in the settings.  This is also why new terminal windows/tabs should be started with default font size.  Since Terminal does not have settings (intentionally, I believe), the idea of being able to save the default zoom level/font size from current one sounds reasonable.

There are cases when a particular tab/window is better shown in dark-on-light (or just different) color scheme. Since Elementary's Terminal does not support profiles this would make it possible.  In `gnome-terminal` and `konsole` it is easy to switch profiles using right-click menu.  I seem to remember this also being possible in Terminal.app on macOS (profiles even include window transparency setting).

So moving the gear (settings) button to the tab bar also makes sense to me.  But then again it might clutter up the tab bar too much.  I also don't think I'd like if the button was only present on the active tab.  Right-click menu sounds like a good place, but might hurt discoverability a bit.  Not sure how big this problem is — Terminal is not an ordinary application for everyday users.

On this same note — it would make sense if search was also per-tab (as it is in browsers, at least Firefox).  Please disregard if it already is, I'm not running Elementary just yet.

Not sure how long the Terminal can live without some form of advanced settings, though.  At first I was very surprised it is not even possible to set my favourite monospace font (customized Iosevka), but changing settings using `dconf-editor` is fine by me.

**Comment by alexeyten** [comment]
@jdz 
> At first I was very surprised it is not even possible to set my favourite monospace font

It's not the UI, but it is possible:
`dconf write /io/elementary/terminal/settings/font '"Iosevka 13"'`

**Comment by jdz** [comment]
@jeremypw This is cool.  I just compiled the `zoom-per-window` and this might just become my preferred terminal now.  Also appreciating that zooming in works with all of `Ctrl-+`, `Ctrl-=` and `Ctrl-KP_PLUS`.

I'll look into getting `Ctrl-PgUp` and `Ctrl-PgDn` to switch tabs.

I'm also used to new terminal windows showing up with default (configured) dimensions.  When I resize a window it is usually because of the content/function of the terminal.  It's very rare that when I create a new terminal window it will have the same purpose and/or content.  This might be fixed by having a `--geometry` command line option since I have a global shortcut key to open a new terminal (I'll probably quickly un-train the `Ctrl-Shift-n` habit with the current behaviour).

Anyway, big thanks for considering my concerns, I'm halfway over to ElementaryOS now (well, almost).

**Comment by jeremypw** [comment]
@jdz Thanks!  It will be up to the UX team as to whether the zoom per tab PR gets merged.  Will probably have to provide an option of maintaining the existing behaviour first. 

Please raise separate issues about your other concerns (if not already raised).
