### ISSUE TITLE
When I type clear it does not clear

### ISSUE THREAD

**Issue by Abdallah-Moh** [elementary/terminal#594]
## What Happened
When I type clear it does not clear it creates double empty lines

## Expected Behavior
The terminal clear

## Steps to Reproduce
Type Clear

## Screenshots
![Screenshot from 2021-06-07 15 40 05](https://user-images.githubusercontent.com/77546233/121027339-2d652000-c7a7-11eb-9e80-d52017a84545.png)

## Platform Information
Elementary os 5

**Comment by jeremypw** [comment]
Please state which version of elementary and Terminal you are using and any non-default settings and configurations.  The `clear`command seems to work as expected on elementary 6 daily.

**Comment by Abdallah-Moh** [comment]
`ls`

**Comment by Abdallah-Moh** [comment]
I tried restarting but no luck

**Comment by Abdallah-Moh** [comment]
All terminal settings are default

**Comment by jeremypw** [comment]
OK, maybe someone will confirm.  Did this command used to work for you in elementary?

**Comment by Abdallah-Moh** [comment]
Yes

**Comment by false-9** [comment]
I can confirm the same problem (elementary OS 5.1.7 Hera).

The clear command makes the cursor jump down what looks to be about a viewports worth of whitespace (note the first time is actually only 1 line below). So what we have is the history stacked above the new line, instead of clearing it altogether and the new line being at the top.

**Comment by jeremypw** [comment]
@false-9  Thanks for the confirmation on Hera.  The last release of Terminal was over a year ago and unfortunately the codebase is now incompatible so there will not be another stable release for Hera.  Hopefully it will not be too long before elementary 6 is released.  I cannot reproduce this issue on elementary 6 although none of the commits since the last release would obviously impact clearing. Maybe it was an upstream issue.

**Comment by false-9** [comment]
For what its worth I've just realized the same problem occurs on my linux mint machine (different hardware).
