### ISSUE TITLE
Font size is reset when terminal is opened anew

### ISSUE THREAD

**Issue by rasmus91** [elementary/terminal#614]
## What Happened
When I reopen the terminal after having altered the font size, it is always set back to 100%

## Expected Behavior
Font size should be remembered, so the next time the terminal is opened, if it was left at 120%, it remains so.

## Steps to Reproduce
1. Open the terminal, and increase the font size by however much you want.
2. Close the terminal
3. Open the terminal and notice that the font size is back to 100%

## Platform Information
elementary OS 6
io.elementary.terminal 6.0.0

**Comment by jeremypw** [comment]
The zoom level per tab is being saved in `io.elementary.terminal.saved-state.tab-zooms` but does not seem to be applied on restore, or is being overridden.  I think this used to work so looks like a regression.

**Comment by jeremypw** [comment]
In my case at least this was being caused by accidentally using a continental number format setting while in a UK English locale and the code was using a locale dependent function to encode the font scale as a string but a locale independent one to convert it back (which failed).  The linked PR uses locale independent conversion in both directions.
