### ISSUE TITLE
Keybinds for micro text editor do not work, making it less efficient to use the editor

### ISSUE THREAD

**Issue by aspizu** [elementary/terminal#676]
### What Happened?

keybinds like ctrl+shift+right don't work

### Steps to Reproduce

start micro editor
use keybinds ctrl+shift+right/left

### Expected Behavior

keybinds should work

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Just tried this on OS7 but I am not familiar with micro, so what do you expect Ctrl + Shift + Left etc to do?  For me it is selecting text.

**Comment by aspizu** [comment]
> Just tried this on OS7 but I am not familiar with micro, so what do you expect Ctrl + Shift + Left etc to do? For me it is selecting text.

yes ctrl+shift+left should select a word towards the left

for me it doesnt work because its the shortcut for switching tabs

there should be a option to disable/change these shortcuts

**Comment by jeremypw** [comment]
Hmm, just tried this again and this time Ctrl+Shift+Left is being captured by Terminal - but I can select text using Shift + Left.  Not sure what was happening the first time.  But yes, keyboard shortcuts should be passed to a foreground process first before being acted on by Terminal.  Introducing a setting to turn off shortcuts would be less likely to find favor.

**Comment by jeremypw** [comment]
I think making the editor "impossible to use" is perhaps overstating the case.

**Comment by aspizu** [comment]
> I think making the editor "impossible to use" is perhaps overstating the case.
It is usable but these keybinds are important to work efficiently

**Comment by stan-janssen** [comment]
How about removing the ctrl + shift + left / right shortcuts for switching tabs, since we already have ctrl + pgup / pgdown for this, and those are consistent with both Files and Web?

After that, we should extend ctrl + pgup and ctrl + pgdown to Code as well, and we’ll have all the elementary default apps on the same shortcuts scheme.

It will also solve this particular problem of not trampling ctrl + shift + left / right for selecting in some of the more advanced TUI text editors.
